version: "3.8"

services:
  # 1. 백엔드 API (NestJS)
  nest-api:
    build: ./nest-api
    env_file:
      - ./nest-api/.env.dev
    ports:
      - "3000:3000"
    volumes:
      - ./nest-api:/app # 내 코드와 도커 내부를 실시간 동기화
      - /app/node_modules # 도커 내부 라이브러리는 덮어쓰지 않음
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: pnpm run start:dev # NestJS 개발 서버(watch 모드) 실행

  # 2. 어드민 페이지 (Vue)
  vue-admin:
    build: ./vue-admin
    env_file:
      - ./nest-api/.env.dev
    ports:
      - "8000:5173" # 외부 8000번 -> 내부 Vite 기본 포트 5173
    volumes:
      - ./vue-admin:/app
      - /app/node_modules
    command: pnpm dev --host # Vite 개발 서버 실행 (--host 필수)

  # 3. 메인 홈페이지 (Vue)
  vue-main:
    build: ./vue-main
    env_file:
      - ./nest-api/.env.dev
    ports:
      - "8001:5173"
    volumes:
      - ./vue-main:/app
      - /app/node_modules
    command: pnpm dev --host

  # 4. 쇼핑몰 페이지 (Vue)
  vue-store:
    build: ./vue-store
    env_file:
      - ./nest-api/.env.dev
    ports:
      - "8002:5173"
    volumes:
      - ./vue-store:/app
      - /app/node_modules
    command: pnpm dev --host

networks:
  default:
    name: codept-network
