# nginx/default.conf

# ==========================================
# 1. API 서버 (nest.js) -> api.codept.kr
# ==========================================
server {
    listen 80;
    server_name api.codept.kr;
    return 301 https://$host$request_uri; # HTTP 접속 시 HTTPS로 강제 리다이렉트
}

server {
    listen 443 ssl;
    server_name api.codept.kr;

    # 공통 인증서 경로 적용
    ssl_certificate /etc/letsencrypt/live/codept.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/codept.kr/privkey.pem;

    location / {
        proxy_pass http://nest-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# ==========================================
# 2. 어드민 페이지 (vue-admin) -> adm.codept.kr
# ==========================================
server {
    listen 80;
    server_name adm.codept.kr;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name adm.codept.kr;

    ssl_certificate /etc/letsencrypt/live/codept.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/codept.kr/privkey.pem;

    location / {
        proxy_pass http://vue-admin:80;
    }
}

# ==========================================
# 3. 메인 홈페이지 (vue-main) -> codept.kr
# ==========================================
server {
    listen 80;
    server_name codept.kr www.codept.kr;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name codept.kr www.codept.kr;

    ssl_certificate /etc/letsencrypt/live/codept.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/codept.kr/privkey.pem;

    location / {
        proxy_pass http://vue-main:80;
    }
}

# ==========================================
# 4. 쇼핑몰 페이지 (vue-store) -> store.codept.kr
# ==========================================
server {
    listen 80;
    server_name store.codept.kr;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name store.codept.kr;

    ssl_certificate /etc/letsencrypt/live/codept.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/codept.kr/privkey.pem;

    location / {
        proxy_pass http://vue-store:80;
    }
}