# nginx/default.conf

# 1. API 서버 (nest.js)
server {
    listen 80;
    server_name api.codept.kr;

    location / {
        # 도커 내부 네트워크에서는 컨테이너 이름(nest-api)으로 통신합니다.
        proxy_pass http://nest-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# 2. 어드민 페이지 (vue-admin)
server {
    listen 80;
    server_name adm.codept.kr;

    location / {
        proxy_pass http://vue-admin:80; # 프로덕션 Dockerfile의 Nginx 포트
    }
}

# 3. 메인 홈페이지 (vue-main)
server {
    listen 80;
    server_name codept.kr www.codept.kr;

    location / {
        proxy_pass http://vue-main:80;
    }
}

# 4. 쇼핑몰 페이지 (vue-store)
server {
    listen 80;
    server_name store.codept.kr;

    location / {
        proxy_pass http://vue-store:80;
    }
}