# nginx/local.conf

# 1. API (api.codept.kr) -> 3000 포트
server {
    listen 80;
    server_name api.codept.kr;
    location / {
        proxy_pass http://host.docker.internal:3000; # 내 로컬 PC의 3000번으로 연결
        proxy_set_header Host $host;
    }
}

# 2. Admin (adm.codept.kr) -> 8000 포트
server {
    listen 80;
    server_name adm.codept.kr;
    location / {
        proxy_pass http://host.docker.internal:8000;
    }
}

# 3. Main (codept.kr) -> 8001 포트
server {
    listen 80;
    server_name codept.kr;
    location / {
        proxy_pass http://host.docker.internal:8001;
    }
}

# 4. Store (store.codept.kr) -> 8002 포트
server {
    listen 80;
    server_name store.codept.kr;
    location / {
        proxy_pass http://host.docker.internal:8002;
    }
}